use winit::keyboard::PhysicalKey;

pub fn physical_key_to_keycode(key: &PhysicalKey) -> u16 {
    match key {
        PhysicalKey::Code(code) => match code {
            winit::keyboard::KeyCode::KeyA => 0x41,
            winit::keyboard::KeyCode::KeyB => 0x42,
            winit::keyboard::KeyCode::KeyC => 0x43,
            winit::keyboard::KeyCode::KeyD => 0x44,
            winit::keyboard::KeyCode::KeyE => 0x45,
            winit::keyboard::KeyCode::KeyF => 0x46,
            winit::keyboard::KeyCode::KeyG => 0x47,
            winit::keyboard::KeyCode::KeyH => 0x48,
            winit::keyboard::KeyCode::KeyI => 0x49,
            winit::keyboard::KeyCode::KeyJ => 0x4A,
            winit::keyboard::KeyCode::KeyK => 0x4B,
            winit::keyboard::KeyCode::KeyL => 0x4C,
            winit::keyboard::KeyCode::KeyM => 0x4D,
            winit::keyboard::KeyCode::KeyN => 0x4E,
            winit::keyboard::KeyCode::KeyO => 0x4F,
            winit::keyboard::KeyCode::KeyP => 0x50,
            winit::keyboard::KeyCode::KeyQ => 0x51,
            winit::keyboard::KeyCode::KeyR => 0x52,
            winit::keyboard::KeyCode::KeyS => 0x53,
            winit::keyboard::KeyCode::KeyT => 0x54,
            winit::keyboard::KeyCode::KeyU => 0x55,
            winit::keyboard::KeyCode::KeyV => 0x56,
            winit::keyboard::KeyCode::KeyW => 0x57,
            winit::keyboard::KeyCode::KeyX => 0x58,
            winit::keyboard::KeyCode::KeyY => 0x59,
            winit::keyboard::KeyCode::KeyZ => 0x5A,

            winit::keyboard::KeyCode::Digit0 => 0x30,
            winit::keyboard::KeyCode::Digit1 => 0x31,
            winit::keyboard::KeyCode::Digit2 => 0x32,
            winit::keyboard::KeyCode::Digit3 => 0x33,
            winit::keyboard::KeyCode::Digit4 => 0x34,
            winit::keyboard::KeyCode::Digit5 => 0x35,
            winit::keyboard::KeyCode::Digit6 => 0x36,
            winit::keyboard::KeyCode::Digit7 => 0x37,
            winit::keyboard::KeyCode::Digit8 => 0x38,
            winit::keyboard::KeyCode::Digit9 => 0x39,

            winit::keyboard::KeyCode::Comma       => 0xBC,
            winit::keyboard::KeyCode::Period      => 0xBE,
            winit::keyboard::KeyCode::Semicolon   => 0xBA,
            winit::keyboard::KeyCode::Quote       => 0xDE,
            winit::keyboard::KeyCode::Slash       => 0xBF,
            winit::keyboard::KeyCode::Backslash   => 0xDC,
            winit::keyboard::KeyCode::BracketLeft => 0xDB,
            winit::keyboard::KeyCode::BracketRight=> 0xDD,
            winit::keyboard::KeyCode::Minus       => 0xBD,
            winit::keyboard::KeyCode::Equal       => 0xBB,

            winit::keyboard::KeyCode::Enter       => 0x0D,
            winit::keyboard::KeyCode::Tab         => 0x09,
            winit::keyboard::KeyCode::Space       => 0x20,
            winit::keyboard::KeyCode::Backspace   => 0x08,
            winit::keyboard::KeyCode::Escape      => 0x1B,

            winit::keyboard::KeyCode::ArrowUp     => 0x26,
            winit::keyboard::KeyCode::ArrowDown   => 0x28,
            winit::keyboard::KeyCode::ArrowLeft   => 0x25,
            winit::keyboard::KeyCode::ArrowRight  => 0x27,

            winit::keyboard::KeyCode::F1  => 0x70,
            winit::keyboard::KeyCode::F2  => 0x71,
            winit::keyboard::KeyCode::F3  => 0x72,
            winit::keyboard::KeyCode::F4  => 0x73,
            winit::keyboard::KeyCode::F5  => 0x74,
            winit::keyboard::KeyCode::F6  => 0x75,
            winit::keyboard::KeyCode::F7  => 0x76,
            winit::keyboard::KeyCode::F8  => 0x77,
            winit::keyboard::KeyCode::F9  => 0x78,
            winit::keyboard::KeyCode::F10 => 0x79,
            winit::keyboard::KeyCode::F11 => 0x7A,
            winit::keyboard::KeyCode::F12 => 0x7B,

            winit::keyboard::KeyCode::ShiftLeft    => 0xA0,
            winit::keyboard::KeyCode::ShiftRight   => 0xA1,
            winit::keyboard::KeyCode::ControlLeft  => 0xA2,
            winit::keyboard::KeyCode::ControlRight => 0xA3,
            winit::keyboard::KeyCode::AltLeft      => 0xA4,
            winit::keyboard::KeyCode::AltRight     => 0xA5,

            winit::keyboard::KeyCode::Insert       => 0x2D,
            winit::keyboard::KeyCode::Delete       => 0x2E,
            winit::keyboard::KeyCode::Home         => 0x24,
            winit::keyboard::KeyCode::End          => 0x23,
            winit::keyboard::KeyCode::PageUp       => 0x21,
            winit::keyboard::KeyCode::PageDown     => 0x22,

            _ => 0x00,
        },
        _ => 0x00,
    }
}
